#!/bin/bash
 iacta est is a Latin phrase that means "the die is cast (thrown)". Suetonius credits Julius Caesar as having said it on January 10, 49 B.C when he led his army across the Rubicon river in Northern Italy.It means things have happened that can't be changed back.
The phrase, either in Latin or in translation, is used in many different languages; Arabic: تم إلقاء الزهر Bulgarian: Зарът е хвърлен Croatian: Kocka je bačena Czech: Kostky jsou vrženy Danish: Terningen er kastet and many other languages.
